---
title: Promise
date: 2022-07-30 13:19:12
tags: ['js', 'ES6']
categories: ['前端']
---

# 1. 多个 Promise 的执行

```js
console.log('ha1')
setTimeout(() => {
  console.log(7)
})

new Promise((resolve, reject) => {
  console.log('ha1')
  resolve('test')
})
  .then(() => {
    console.log(0)
    return Promise.resolve(4)
  })
  .then((res) => {
    console.log(res)
  })

new Promise((resolve, reject) => {
  console.log('ha2')
  resolve('666')
})
  .then(() => {
    console.log(2)
  })
  .then(() => {
    console.log(3)
  })
  .then(() => {
    console.log(5)
  })
  .then(() => {
    console.log(6)
  })
```

# 2. resolve promise 自身的几种情况

## 2.1 let 定义

```js
let pro1 = new Promise((resolve, reject) => {
  resolve(pro1)
})

pro1.then(
  (res) => {
    console.log('pro1..res..', res)
  },
  (err) => {
    console.log('pro1..err..', err)
  }
)
```

## 2.2 const 定义

```js
const pro1 = new Promise((resolve, reject) => {
  resolve(pro1)
})

pro1.then(
  (res) => {
    console.log('pro1..res..', res)
  },
  (err) => {
    console.log('pro1..err..', err)
  }
)
```

## 2.3 var 定义

```js
var pro1 = new Promise((resolve, reject) => {
  resolve(pro1)
})

pro1.then(
  (res) => {
    console.log('pro1..res..', res)
  },
  (err) => {
    console.log('pro1..err..', err)
  }
)
```

# 3. then 方法

## 3.1 onFulfilled 及 onRejected 返回值

```js
var p = new Promise((resolve, reject) => {
  resolve('p..success')
})

var p2 = p.then(
  (res) => {
    console.log('p..res', res)
    return 'p.res' // 如果没有return语句呢? 试试去掉return
  },
  (err) => {
    console.log('p..err', err)
    return 'p.err'
  }
)

p2.then(
  (res) => {
    console.log('p2..res', res)
  },
  (err) => {
    console.log('p2..err', err)
  }
)
```

```js
var p = new Promise((resolve, reject) => {
  console.log('第一层')
  resolve('第一层的resolve')
})
  .then(
    (res) => {
      console.log('p..res', res)
      return new Promise((resolve, reject) => {
        console.log('这是什么')
        resolve('look at this')
      })
    },
    (err) => {
      console.log('p..err', err)
    }
  )
  .then(
    (res) => {
      console.log('第三层..res', res)
    },
    (err) => {
      console.log('第三层..err', err)
    }
  )
```

## 3.2 onFulfilled 或者 onRejected 省略的情况

```js
var p = new Promise((resolve, reject) => {
  resolve('p..success')
})

p.then()
  .then()
  .then(
    (res) => {
      console.log('p...res', res)
    },
    (err) => {
      console.log('p...err', err)
    }
  )

// 或者
var p = new Promise((resolve, reject) => {
  reject('p..reject')
})

p.then()
  .then()
  .then(
    (res) => {
      console.log('p...res', res)
    },
    (err) => {
      console.log('p...err', err)
    }
  )

// 又或者
var p = new Promise((resolve, reject) => {
  reject('p..reject')
})

p.then('abc', 'efg')
  .then()
  .then(
    (res) => {
      console.log('p...res', res)
    },
    (err) => {
      console.log('p...err', err)
    }
  )
```

## 3.3 onFulfiled 或者 onRejected 有异常的情况下

```js
var p = new Promise((resolve, reject) => {
  resolve('p...success')
})
  .then(
    (res) => {
      console.log('p...res', res)
      console.log(a + b)
      return 'r.res'
    },
    (err) => {
      console.log('p...err', err)
    }
  )
  .then(
    (res) => {
      console.log('p2...res', res)
    },
    (err) => {
      console.log('p2...err', err)
    }
  )
```

# 4. promise resolve 的解析过程

## 4.1 resolve 或者 reject 一个 promise

```js
var p = new Promise((resolve, reject) => {
  resolve(
    new Promise((resolve2, reject2) => {
      resolve('这是内部的resolve')
    })
  )
})

p.then(
  (res) => {
    console.log('p..res', res)
  },
  (err) => {
    console.log('p..err', err)
  }
)

// reject
var p = new Promise((resolve, reject) => {
  reject(
    new Promise((resolve2, reject2) => {
      resolve2('这是内部的resolve')
    })
  )
})

p.then(
  (res) => {
    console.log('p...res', res)
  },
  (err) => {
    console.log('p...err', err)
  }
)
```

# 5. then 方法链式调用

```js
var p = new Promise((resolve, reject) => {
  console.log('第一层')
  resolve('第一层的resolve')
})

p.then(
  (res) => {
    console.log('p..res', res)
    return '第二层..'
  },
  (err) => {
    console.log('p..err', err)
  }
).then(
  (res) => {
    console.log('第三层..res', res)
  },
  (err) => {
    console.log('第三层..err', err)
  }
)
```
